version: "3.8"

services:
  mysql-8.0.41:
    image: mysql:8.0.41
    container_name: mysql-8.0.41
    restart: always
    environment:
      MYSQL_DATABASE: audiva
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - audiva-net

  audiva:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiva
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-8.0.41
    environment:
      DBMS_CONNECTION: jdbc:mysql://mysql-8.0.41:3306/audiva
      DBMS_USERNAME: root
      DBMS_PASSWORD: root
    networks:
      - audiva-net

volumes:
  mysql-data:

networks:
  audiva-net:
