server:
  port: 8080
  servlet:
    context-path: /identity
  multipart:
    max-file-size: 50MB
    max-request-size: 100MB

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/audiva"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  signerKey: "1a92f26d86514e94c5991ca2afa01e6680d70b94518e8508541e1ea90f6106f9"
  accessTokenExpiration: 900
  refreshTokenExpiration: 604800

vnpay:
  tmn-code: Z0K7KAKL
  hash-secret: SLM2ZXMO9LNC6JTSC3RI4XHYW6K1JEAU
  vnp-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  vnp-return-url: http://localhost:8080/identity/api/premium/payment-return